export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const GITHUB_SUCCESS = "LOGIN_SUCCESS";
export const GITHUB_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const ARTICLE_CREATE = "ARTICLE_CREATE";
export const ARTICLE_UPDATE = "ARTICLE_UPDATE";
export const ARTICLE_RETRIEVE = "ARTICLE_RETRIEVE";
export const ARTICLE_DELETE = "ARTICLE_DELETE";
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const COMMENT_RETRIEVE = "COMMENT_RETRIEVE"
export const COMMENT_CREATE = "COMMENT_CREATE"
export const COMMENT_UPDATE = "COMMENT_UPDATE"
export const COMMENT_DELETE = "COMMENT_DELETE"

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
